version: '3.8'

services:
  #BASE DE DATOS (Redis)
  redis:
    image: redis:alpine
    container_name: mandalorian_redis
  
    command: redis-server --appendonly yes
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network
  
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5


  # BACKEND (API Python Flask)

  backend:
    build: ./backend
    container_name: mandalorian_api
    ports:
      - "${API_PORT}:5000"
    volumes:
      - ./backend:/app
    environment:
   
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=5000
    depends_on:
      redis:
        condition: service_healthy # Espera a que Redis est√© sano
    networks:
      - app_network

  # FRONTEND (React Vite)

  frontend:
    build: ./frontend
    container_name: mandalorian_web
    ports:
      - "${WEB_PORT}:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
   
      - VITE_API_URL=http://localhost:${API_PORT}
    networks:
      - app_network


volumes:
  redis_data:


networks:
  app_network:
    driver: bridge
